Repository mirage-software/Kabooty, pull requests merged in 2022-07, with the labels that each got.

#11 Update Readme
  README.md
Labels: documentation, enhancement

#18 Series in PickCard
  src/components/collabs/pick.svelte
  src/components/profile/picks.svelte
  src/routes/api/collabs/[id]/picks/index.ts
  src/routes/api/picks/index.ts
Labels: enhancement, P4, UI, UX

#20 missing declaraton in index + lowercase
  src/components/collabs/pick.svelte
  src/components/profile/picks.svelte
  src/routes/collabs/[id]/index.svelte
Labels: P4, Backend

#21 Sort filter picks
  prisma/schema.prisma
  src/components/collabs/register/character.svelte
  src/components/collabs/register/extra/dropdown.svelte
  src/components/generic/design/input_text.svelte
  src/routes/admin/characters.svelte
  src/routes/api/characters.ts
  src/routes/api/collabs/[id]/characters.ts
  src/routes/api/collabs/[id]/picks/index.ts
  src/routes/collabs/[id]/index.svelte
  src/routes/redirect/osu.svelte
  static/locales/en.json
Labels: enhancement, P2, UI, Backend

#23 more responsive dropdown
  src/components/collabs/register/extra/dropdown.svelte
  src/routes/collabs/[id]/index.svelte
Labels: enhancement, P2, UI

#29 added Internal db sort based on character search
  docker-compose.yml
  src/routes/admin/characters.svelte
  src/routes/api/characters.ts
Labels: enhancement, P1, UI, Backend

#31 add pagination to character select + fixed pagination not showing 2 button on 3 pages
  src/components/collabs/register/character.svelte
  src/components/generic/design/paginator.svelte
  src/routes/api/collabs/[id]/characters.ts
Labels: enhancement, P1, UI, Backend

#38 Fix for Admin Database singe character import
  src/routes/admin/characters.svelte
Labels: bug, enhancement, P1

#39 added a way to delete reports
  src/bot/discord.ts
  src/bot/handleInteraction.ts
  src/routes/api/collabs/[id]/picks/[pick_id]/report.ts
Labels: enhancement, P1, Backend
