Repository mirage-software/Kabooty, pull requests merged in 2022-08, with the labels that each got.

#42 filter for discorid and discord#
  src/routes/api/collabs/[id]/picks/index.ts
Labels: enhancement, P4, UI

#33 Deletion Notifier on discord channel
  .env.example
  src/components/collabs/pick.svelte
  src/routes/api/collabs/[id]/picks/[pick_id]/index.ts
Labels: enhancement, P1, Backend

#40 Allow the deletion of images
  src/components/collabs/pick.svelte
  src/routes/api/collabs/[id]/picks/[pick_id]/image.ts
  static/locales/en.json
Labels: enhancement, P2, UI

#43 quick fixes
  docker-compose.yml
  src/components/collabs/pick.svelte
  src/routes/api/collabs/[id]/picks/[pick_id]/index.ts
Labels: bug, enhancement, P1
